/* Copies the generated assets to the two places that actually get served, and
   writes the <head> snippet. Run after brand/make.js. */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'out');
const ROOT = path.join(__dirname, '..');
const DEST = [path.join(ROOT, 'public'), path.join(ROOT, 'landing-site')];

/* What the browser needs to see at the site root. */
const WEB = [
  'favicon.ico', 'favicon.svg', 'favicon-16.png', 'favicon-32.png',
  'apple-touch-icon.png', 'android-chrome-192.png', 'android-chrome-512.png',
  'android-chrome-maskable-512.png', 'mstile-150.png', 'site.webmanifest',
  'og-image.png'
];

for (const dir of DEST) {
  if (!fs.existsSync(dir)) { console.log('skip (no such folder): ' + dir); continue; }
  let n = 0, bytes = 0;
  for (const f of WEB) {
    const from = path.join(OUT, f);
    if (!fs.existsSync(from)) { console.log('MISSING ' + f); continue; }
    const to = path.join(dir, f);
    fs.copyFileSync(from, to);
    n++; bytes += fs.statSync(to).size;
  }
  console.log(path.relative(ROOT, dir).padEnd(14) + n + ' files, ' + (bytes / 1024).toFixed(1) + ' KB');
}

/* The exact head block. Kept in a file so the app and the landing page can't
   drift - paste it, don't retype it. */
const SNIPPET = `<!-- icons:start - generated by brand/install.js, do not hand-edit -->
<link rel="icon" href="/favicon.ico" sizes="any"/>
<link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png"/>
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="manifest" href="/site.webmanifest"/>
<meta name="theme-color" content="#4f8cff"/>

<meta property="og:type" content="website"/>
<meta property="og:site_name" content="Get It?"/>
<meta property="og:title" content="Get It? - do they actually understand it?"/>
<meta property="og:description" content="Find out in two minutes who really understood your lesson - and who is quietly faking it."/>
<meta property="og:image" content="__BASE__/og-image.png"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<meta property="og:image:alt" content="You taught it. Did they get it? - Get It?"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="Get It? - do they actually understand it?"/>
<meta name="twitter:description" content="Find out in two minutes who really understood your lesson - and who is quietly faking it."/>
<meta name="twitter:image" content="__BASE__/og-image.png"/>
<!-- icons:end -->
`;
fs.writeFileSync(path.join(OUT, 'head-snippet.html'), SNIPPET);
console.log('wrote brand/out/head-snippet.html');
